// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy8TEDeaYAQCyvk4Zt-23Q2bTST1A_FHs',
    appId: '1:674146958822:web:48170304313b411e80ea27',
    messagingSenderId: '674146958822',
    projectId: 'hostel-management-9b5cc',
    authDomain: 'hostel-management-9b5cc.firebaseapp.com',
    storageBucket: 'hostel-management-9b5cc.firebasestorage.app',
    measurementId: 'G-99GL4D6VF5',
    databaseURL:
        'https://hostel-management-9b5cc-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWk7fEGCUXkthqdisei9z-hm437ZbVNRM',
    appId: '1:674146958822:android:8ccebd8c38601fb580ea27',
    messagingSenderId: '674146958822',
    projectId: 'hostel-management-9b5cc',
    storageBucket: 'hostel-management-9b5cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr-loDY_q1HDlvbfH0zD8m028rB8c3TdE',
    appId: '1:674146958822:ios:70b0254842106acd80ea27',
    messagingSenderId: '674146958822',
    projectId: 'hostel-management-9b5cc',
    storageBucket: 'hostel-management-9b5cc.firebasestorage.app',
    iosBundleId: 'com.rashid.hostelManagement',
  );
}
